### ISSUE TITLE
Github import - use user's github username by default

### ISSUE THREAD

**Issue by Marie000** [danamn/OpenCodeReviewer#25]
But allow to replace with another username.

**Comment by saracarlile** [comment]
I tried doing the Github import to add code for review in your app, but the code didn't seem to import right.   I created the "Image Search Abstraction" post from my repository https://github.com/saracarlile/image-search-abstraction.  
I can try again if you give me steps that should make it work.

**Comment by Marie000** [comment]
That should be fixed. Let me know if you still have problems.

**Comment by saracarlile** [comment]
I am still having issues with the github import.  I tried emptying my browser cache.  Are you importing a project that only has one file?  The ones I am trying have multiple files.

**Comment by Marie000** [comment]
Oh, yes. Right now the app only handles one file at a time.
Eventually it will allow you to import a whole repo, but that's still on the todo list.
