### ISSUE TITLE
Error: API key ID and secret is required.

### ISSUE THREAD

**Issue by saracarlile** [danamn/OpenCodeReviewer#34]
I forked the repository, cloned it, and then tried running npm start so I could view it at localhost:9000.
I received the error in the console:
'Error: API key ID and secret is required.'
It looks like you have the file 'apiKey.properties' for stormpath .gitignor-ed (understandably!) but this makes it difficult to work on the project locally since I can't run it.

**Comment by Marie000** [comment]
you will need to create a free stormpath account. 
Once you have that, in your console, set the api key, api secret and href:
```
export STORMPATH_CLIENT_APIKEY_ID=YOUR_ID_HERE
export STORMPATH_CLIENT_APIKEY_SECRET=YOUR_SECRET_HERE
export STORMPATH_APPLICATION_HREF=YOUR_APP_HREF
```
(if in Windows, replace export with set)

**Comment by Marie000** [comment]
Did you manage to make it work?

**Comment by saracarlile** [comment]
Yes, I can run your project locally now with these instructions in addition to what you posted on FB.  Thanks!

**Comment by saracarlile** [comment]
I just did a git pull upstream master, and noticed that your apiKey file is now saved to your repository in the root directory.

**Comment by Marie000** [comment]
yep. the api key file should not be there. But I will be switching to a new auth service anyways, so it doesn't matter.
